############################################################################################
#
#                                   LTProxy
#                                           by L
#
#----------------------------------- Format ------------------------------------------------
# rules:
#   - proxies:
#       - <socks_type> <host> <port> [username] [password]
#       - ...
#     target:
#       - <target> <ports>
#       - ...
# 
#   - ...
# 
# 字段解释
# proxies:
#   socks_type    代理的类型，目前支持 socks5/socks4/socks4a (最后一层代理目前仅支持 socks5)
#   host          代理地址
#   port          代理端口
#   username      如需认证可添上
#   password      如需认证可添上
# target:
#   target        需要透明代理的目标地址，支持格式：192.168.*.* 10.0.0.0/8 192.168.1.1 等
#                 还支持别名 intranet extranet any，用于内网、外网和所有的选择
#   ports         可选默认 any, 支持格式：22,8000-9000 等
#
# ----------------------------------- Example ----------------------------------------------
#
# rules:
#   - proxies:
#       - direct
#     target:
#       - 192.168.12.*
# 
#   - proxies:
#       - socks5 12.12.12.12 1080 twelve password
#       - socks4 172.16.1.2 1088
#       - socks5 19.128.1.2 8888 admin admin
#     target:
#       - 19.*.*.*
#       - 1.1.1.1
#       - intranet 22,7000-9000
#       - 18.7.0.0/16
# 
#   - proxies:
#       - socks5 21.21.21.21 1080
#     target:
#       - extranet
#
#
############################################################################################

rules:
  - proxies:
      - socks5 12.12.12.12 1080
    target:
      - 192.168.*.*
